#%RAML 1.0 NamedExample
value:
-
  id: "1"
  firstName: Max
  lastName: Mule
  address: 4040 Briar Thorn, Crawfordsville, IN
  postal: "47903"
  country: USA
  miles: 200
  creationDate: 2020-09-28T12:00:00.000Z
  type: personal
-
  id: "2"
  firstName: Morgan
  lastName: Dockerman
  address: 3893 Cactus Circle, St Paul, MN
  postal: "53222"
  country: USA
  miles: 800
  creationDate: 2021-04-28T09:23:13.010Z
  type: business