#%RAML 1.0 NamedExample
value:
-
  firstName: Max
  lastName: Mule
  address: 4040 Briar Thorn, Crawfordsville, IN
  postal: "47903"
  country: USA
  miles: 200
  type: personal
-
  firstName: Morgan
  lastName: Dockerman
  address: 3893 Cactus Circle, St Paul, MN
  postal: "53222"
  country: USA
  miles: 800
  type: business
